### ISSUE TITLE
UnicodeEncodeError when trying to parse with Mortal engine

### ISSUE THREAD

**Issue by hyskylord** [Equim-chan/mjai-reviewer#72]
Hi,

  I managed to train a basic Mortal model and when I try to review Tenhou logs, I get the following error:
```
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb3' in position 39: surrogates not allowed
```
  which seems to be a pipeline encoding problem. I am running in Windows 11 powershell.

**Comment by Equim-chan** [comment]
You didn't even write the steps to reproduce.

**Comment by Equim-chan** [comment]
You should include the steps to reproduce.

**Comment by hyskylord** [comment]
Full logs:
```
(mortal) PS C:\Users\****\source\repos\mjai-reviewer\target\release> .\mjai-reviewer --url "http://tenhou.net/0/?log=2021122200gm-00a9-0000-a5ac98ec" --out-file 1234.json --mjai-out 123.json --engine mortal
23:34:24.857283 src\main.rs:258 converting to mjai events...
23:34:24.870621 src\main.rs:293 players: サン&ムーン, 侍, 夏なのに, tenhou君
23:34:24.871000 src\main.rs:294 target: サン&ムーン (0)
Traceback (most recent call last):
  File "C:\Users\****\source\repos\mjai-reviewer\target\release\Mortal\mortal.py", line 77, in <module>
    main()
  File "C:\Users\****\source\repos\mjai-reviewer\target\release\Mortal\mortal.py", line 53, in main
    if reaction := bot.react(line):
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb3' in position 39: surrogates not allowed
Error: failed to review

Caused by:
    failed to read from engine: unexpected EOF
```

**Comment by Equim-chan** [comment]
I think it's related to the locale, what is the output of `python -c 'import sys; print(sys.getdefaultencoding())'` in your environment?

**Comment by hyskylord** [comment]
it's UTF-8.

**Comment by hyskylord** [comment]
Problem solved. Thanks!
